.rubocop.yml, lib/crawler/api/crawl.rb, lib/crawler/coordinator.rb, lib/crawler/http_client.rb, lib/crawler/http_utils/response.rb, lib/crawler/output_sink/elasticsearch.rb, lib/errors.rb, lib/utility/bulk_queue.rb, lib/utility/es_client.rb, spec/lib/crawler/coordinator_spec.rb, spec/lib/crawler/output_sink/elasticsearch_spec.rb, spec/lib/utility/bulk_queue_spec.rb
The coordinator currently doesn't care about the state of the bulk queue, and will add a crawl result to the queue pool whenever it is finished crawling a page.
This is not thread-safe as multiple threads attempting to add to the queue causes overwrites and potentially lost data.
This is more noticeable since implementing [retries with exponential backoff for ES indexing](https://github.com/elastic/crawler/pull/39).
This change adds a mutex lock to the `write` method in the `Elasticsearch` sink. If `write` is called, the lock is enabled, and nothing can be added to the pool until the lock is lifted.
This effectively pauses crawl requests when ES indexing is overloaded. This should only impact performance if an ES instance is unhealthy or there are network issues. I think this is …
=> Lock bulk queue while processing indexing request

config/crawler.yml.example, config/examples/parks-australia.yml, lib/crawler/api/config.rb, spec/fixtures/crawl.yml, spec/integration/timeouts/request_timeout_spec.rb, spec/lib/crawler/api/config_spec.rb, spec/lib/crawler/api/crawl_spec.rb, spec/lib/crawler/coordinator_spec.rb, spec/lib/crawler/data/url_queue/memory_only_spec.rb, spec/lib/crawler/data/url_queue_spec.rb, spec/lib/crawler/event_generator_spec.rb, spec/lib/crawler/http_client_spec.rb, spec/lib/crawler/output_sink/elasticsearch_spec.rb, spec/lib/crawler/output_sink/file_spec.rb, spec/lib/crawler/output_sink_spec.rb, spec/lib/crawler/rule_engine/base_spec.rb, spec/support/faux/faux_crawl.rb
Currently all configured domains to crawl are included in a single array, `domain_allowlist`. As we move to implement domain-specific configurations, it is necessary to have each domain separated into its own entity. Using this starting point it will be easier to add domain-specific configurations like extraction rules.
The format change is handled entirely within the `Crawler::Api::Config` class. The class object created is still identical to before so this will have no impact on other parts of the codebase. Only the input parameters are changed.
- Crawler config.yml now has a `domains` key at base that takes an array. Each item in the array corresponds to 1 domain.
- `domain_allowlist` is now `domains[].url`
- `seed_urls` are now optional, if they aren't provided then the domain's `url` …
=> Update domains format in crawler config.yml

README.md, config/crawler.yml.example, docs/CONTENT_EXTRACTION.md, docs/DOCUMENT_SCHEMA.md, lib/constants.rb, lib/crawler/api/config.rb, lib/crawler/data/extraction/rule.rb, lib/crawler/data/extraction/ruleset.rb, lib/crawler/data/extraction/url_filter.rb, spec/lib/crawler/data/extraction/rule_spec.rb, spec/lib/crawler/data/extraction/ruleset_spec.rb, spec/lib/crawler/data/extraction/url_filter_spec.rb
This is the first step in enabling CSS, XPATH and URL content extraction.
- Add classes for managing extraction rules config
- Set up per-URL content extraction config on startup
- Add documentation
=> Add extraction rules config classes

docs/DOCUMENT_SCHEMA.md, lib/constants.rb, lib/crawler/document_mapper.rb, spec/lib/crawler/output_sink/elasticsearch_spec.rb, spec/lib/utility/es_client_spec.rb
Rename the `body_content` field on indexed docs to `body` to keep it in-line with Connectors doc format.
=> Change field body_content to body

Gemfile.lock
Resolves the following dependabot alerts:
- https://github.com/elastic/crawler/security/dependabot/1
- https://github.com/elastic/crawler/security/dependabot/2
- https://github.com/elastic/crawler/security/dependabot/3
=> Bump rexml to 3.3.4

lib/crawler/data/crawl_result/error.rb
Rename instances of fatal error to internal error, and add a comment description on the error init explaining what the internal error is used for.
Follow up from https://github.com/elastic/crawler/pull/63
=> Rename fatal error to internal error

renovate.json
https://github.com/renovatebot/renovate/discussions/30782 seems to indicate that JRuby isn't really supported by renovate right now. Rather than manually fight each generated update, we'll just disable for now, but leave in place chainguard support for when we leverage wolfi images.
=> Update renovate to only consider chainguard

.buildkite/release-pipeline.yml, catalog-info.yaml
Update the `catalog-info.yaml` in a separate PR to try to get the buildkite endpoint to exist.
=> Update catalog-info.yaml for docker publishing

.buildkite/release-pipeline.yml, catalog-info.yaml
This will backport the following commits from `main` to `0.1`:
- [Update catalog-info.yaml for docker publishing (#104)](https://github.com/elastic/crawler/pull/104)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
=> [0.1] Update catalog-info.yaml for docker publishing (#104)

Dockerfile.wolfi
Add a wolfi version of the Dockerfile so we build from wolfi images.
The existing Dockerfile still works and is unchanged. This wolfi image will be the dockerfile we publish official images from.
=> Add Dockerfile.wolfi

Gemfile, Gemfile.lock, NOTICE.txt, README.md, config/crawler.yml.example, lib/crawler/api/config.rb, lib/crawler/cli.rb, lib/crawler/cli/schedule.rb, spec/fixtures/crawl.yml, spec/lib/crawler/cli/schedule_spec.rb
In the process of writing documentation for cron-based scheduling through bash scripts, I realised the UX was _terrible_. I looked around for an alternative and found [a library called `rufus-scheduler`](https://github.com/jmettraux/rufus-scheduler) that was really easy to tie into the existing CLI to allow for a `bin/crawler schedule` command.
- Add the `bin/crawler schedule` CLI command
- Add `schedule.pattern` config value
- This is a hash for future-proofing, in case we decide to support multiple schedule types instead of just cron expressions
- Use `rufus-scheduler` to create non-overlapping, recurrent crawl jobs
- Update documentation and example config file
I couldn't figure out an effective way to test the `overlapping: false` argument for `rufus-scheduler`. I tested it locally …
=> Add scheduling CLI command

config/crawler.yml.example, docs/DOCUMENT_SCHEMA.md, docs/features/EXTRACTION_RULES.md
- Rename `CONTENT_EXTRACTION.md` to `EXTRACTION_RULES.md` to better align with the actual feature name
- Add example configurations to `EXTRACTION_RULES.md`
=> Add extraction rules examples

docs/CLI.md
- Add `schedule` command docs to `CLI.md`
=> Add schedule command to CLI docs

Dockerfile.wolfi
In `Dockerfile.wolfi`:
* switch back to the `java` user for running the application itself
* use newer `ENV=` syntax
* remove `/app/.git` from the image to decrease size
=> Misc fixes to the Wolfi-based Dockerfile

README.md, docs/CHANGELOG.md
- Add `CHANGELOG.md` with changes taken from `release_note` PRs
- It's not automated yet, but one day
- Change tech-preview to beta
=> Add CHANGELOG.md and upgrade to beta

README.md
- Add docs explaining how to pull and run the official docker image
- Remove docs explaining how to build Dockerfile locally
=> Add docs for running official docker image

lib/crawler/api/crawl.rb, lib/crawler/coordinator.rb
Fix the crawl result log to correctly display `success` when no purge crawl was required.
- Update crawl stage status when skipping purge crawls
- Log correct outcome message in final log
=> Fix crawl result logs

lib/crawler/output_sink/file.rb
The output sink `Crawler::OutputSink::File` was calling the in-built lib `File`, but was confusing that lib for itself.
This forces the usage of `::File` so that ruby knows to use the internal lib instead.
(I'm not sure how this worked before, but possibly caused by upgrading the jruby version?)
🐛  Fixed a bug that caused the `file` output sink to not work
=> Fix usage of in-built `File` lib

catalog-info.yaml
As part of the global Search team's renaming, it's required to update the `ent-search-eng` team to the `search-eng`.
This PR is dedicated to renaming the `ent-search-eng` GitHub team to the `search-eng` team
=> Update ent-search-eng team to be a search-eng team

README.md
When we just follow the instructions in the README, without configuring any scheduler yet (which is the next step), calling the following command does not work:
```sh
docker exec -it crawler bin/crawler schedule config/my-crawler.yml 
```
It fails with:
```
ArgumentError: No schedule found in config file
call at /app/lib/crawler/cli/schedule.rb:25
perform_registry at /usr/local/bundle/gems/dry-cli-0.7.0/lib/dry/cli.rb:116
call at /usr/local/bundle/gems/dry-cli-0.7.0/lib/dry/cli.rb:65
<main> at bin/crawler:28
```
Which is expected as we did not configure yet any schedule. So running the following command for the first time seems to be better:
```sh
docker exec -it crawler bin/crawler crawl config/my-crawler.yml 
```
=> Use crawl for the first step vs schedule

Gemfile, Gemfile.lock
Pin `rexml` to 3.3.8 as 3.3.5 is insecure, see https://github.com/advisories/GHSA-vmwr-mc7x-5vc3
=> Pin rexml version to 3.3.8

spec/lib/crawler/url_validator/crawl_rules_check_spec.rb, spec/lib/crawler/url_validator/dns_check_spec.rb, spec/lib/crawler/url_validator/domain_access_check_spec.rb, spec/lib/crawler/url_validator/domain_uniqueness_check_spec.rb, spec/lib/crawler/url_validator/robots_txt_check_spec.rb, spec/lib/crawler/url_validator/tcp_check_spec.rb, spec/lib/crawler/url_validator/url_check_spec.rb, spec/lib/crawler/url_validator/url_content_check_spec.rb, spec/lib/crawler/url_validator/url_request_check_spec.rb, spec/lib/crawler/url_validator_spec.rb
This is a ad-hoc/trivial change. By reading the [test section in contribution](https://github.com/elastic/crawler/blob/main/docs/CONTRIBUTING.md#testing) found out the intended coverage is 92% of code. While building locally and running the tests found out the url validator related code test coverage could increase and decided to contribute with few rspec tests.  Please let me know if the changes are in alignment with expectations in relation to code style. 
---
Current coverage: 
Coverage after new tests:
---
=> Increases test coverage for url validator code

lib/crawler/api/config.rb, spec/lib/crawler/api/config_spec.rb, spec/lib/crawler/api/crawl_spec.rb, spec/lib/crawler/coordinator_spec.rb, spec/lib/crawler/output_sink_spec.rb
Issue #174 , 
I have replaced console with elasticsearch. Please let me know if any other changes are needed.
=> Make elasticsearch the default value for output_sink

lib/crawler/output_sink/elasticsearch.rb, spec/lib/crawler/output_sink/elasticsearch_spec.rb
Fixes empty pipeline param being sent when pipelines are disabled.
=> Fixes #179 - Omits the pipeline key when pipeline_enabled: false

lib/crawler/output_sink/elasticsearch.rb, lib/errors.rb, spec/lib/crawler/api/crawl_spec.rb, spec/lib/crawler/coordinator_spec.rb, spec/lib/crawler/output_sink/elasticsearch_spec.rb, spec/lib/crawler/output_sink_spec.rb
This PR aims to add a check during the initialization phase of the Elasticsearch output sink that will:
1. Check if the the ES index provided in the config is reachable by Open Crawler
2. Terminate if it is not
3. Output a relevant log message
Ultimately, we do not want the crawl to begin without making sure the index is actually reachable first!
=> Adding check to ES sink to check if index is present before crawling

README.md, config/crawler.yml.example
Related to https://github.com/elastic/crawler/issues/195
The `scheduling.pattern` config should be an object, not an array.
=> Fix scheduling documentation

Dockerfile, Dockerfile.wolfi
Part of security hardening: remove `/root/.m2` directory after the installation has happened.
It seems like it's not needed as it keeps Maven cache, but we already vendor all dependencies on `make install`.
This way we won't distribute any compile-time dependencies, reducing our potential attack surface.
=> Update docker files to remove /root/.m2 directory after installation to not distribute build dependencies

lib/crawler/output_sink/elasticsearch.rb, lib/errors.rb, spec/lib/crawler/api/crawl_spec.rb, spec/lib/crawler/coordinator_spec.rb, spec/lib/crawler/output_sink/elasticsearch_spec.rb, spec/lib/crawler/output_sink_spec.rb
This is a continuation of issue #53 but also closes #172.
This PR will add the following steps during the initialization of the ES Sink:
- A verification step that checks if crawler can reach the Elasticsearch instance provided in configs
- An explicit attempt to create the output_index should the index ping fail (index ping step was added in #186 )
Thus, the flow during init will be like:
`verify ES connection`--> `if all good, verify the output_index `--> `if index does not exist, attempt to create the index` --> `if index creation fails, system exit`
Additional background:
While working on this, I discovered that _technically speaking_, the _bulk command that Crawler uses to upsert documents is capable of auto-creating the index if it doesn't exist. However, this is dependent on the …
=> Adding ES verification step + explicit best-effort index creation during ES Sink initialization

lib/crawler/output_sink/elasticsearch.rb, spec/lib/crawler/api/crawl_spec.rb, spec/lib/crawler/coordinator_spec.rb, spec/lib/crawler/output_sink/elasticsearch_spec.rb, spec/lib/crawler/output_sink_spec.rb
In ES 9.0 the pipeline `ent-search-generic-ingestion` is being replaced by `search-default-ingestion`.
Because we don't have a dedicated Crawler major version for 9.0, it's necessary that Crawler can run on both 8.x and 9.x.
- Add pipeline for 9.x `search-default-ingestion`
- Determine pipeline by checking response from `/info` during preflight check
- Add tests
=> Add ingest pipeline for 9.x

config/crawler.yml.example, lib/crawler/api/config.rb, lib/crawler/document_mapper.rb, spec/lib/crawler/document_mapper_spec.rb
Enable full HTML extraction through a config option.
The logic for this was already present in Crawler code, we were just missing two pieces: a configuration option, and to include the full HTML in the JSON to be ingested to ES.
- Add configuration `full_html_extraction_enabled` which defaults to `false`
- If enabled, include the full HTML in the crawl result doc under field `full_html`
- If disabled, don't include the field `full_html` at all
- (Bonus) add `purge_crawl_enabled` to example YAML file as it was missing
=> Allow for full HTML extraction

lib/crawler/output_sink/elasticsearch.rb, spec/lib/crawler/api/crawl_spec.rb, spec/lib/crawler/coordinator_spec.rb, spec/lib/crawler/output_sink/elasticsearch_spec.rb, spec/lib/crawler/output_sink_spec.rb
This will backport the following commits from `main` to `0.2`:
- [Add ingest pipeline for 9.x (#203)](https://github.com/elastic/crawler/pull/203)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
=> [0.2] Add ingest pipeline for 9.x (#203)

docker-compose.yaml
0.2.1 was just released and is our latest version, so bump the default version in docker-compose so new users can use it.
=> Update default docker-compose version

.buildkite/publish/build-and-push-multiarch-docker.sh, .buildkite/publish/publish-common.sh, .buildkite/release-pipeline.yml, README.md
This will backport the following commits from `main` to `0.2`:
- [Add&#x60;:latest&#x60; tag option to build jobs (#214)](https://github.com/elastic/crawler/pull/214)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
=> [0.2] Add&#x60;:latest&#x60; tag option to build jobs (#214)

docker-compose.yaml
Add comment and environment variable to `docker-compose.yml `for M4 users to comment out in order to run Open Crawler
=> Add environment variable for M4 users

lib/crawler/output_sink/elasticsearch.rb, spec/lib/crawler/output_sink/elasticsearch_spec.rb
Check if build flavor is `serverless` on preflight check, and if it is apply the newer default ingest pipeline.
This allows 8.x serverless scenarios to use the correct pipeline.
=> Check for build flavor as well as ES version during preflight check

README.md
Related to https://github.com/elastic/crawler/issues/222
Add a link to the official docker image at the top of the README
=> Add link to docker image

README.md
Closes https://github.com/elastic/crawler/issues/224
`all` is not required to run a crawl, `monitor` is sufficient.
=> Update API key permissions in README

Dockerfile.wolfi
Installing older curl seems to be linked to vulnerability as reported by SNYK, trying to install newer version of curl
Relates to: [9092](https://github.com/elastic/search-team/issues/9092)
=> chore: install latest curl

Dockerfile.wolfi
- Pin `libcurl-openssl4` to `8.12.1` and ensure it is added before `curl`
- Pin `curl` to `8.12.1`
curl 8.12.x has a dependency on libcurl, but due to a version mismatch in the wolfi image, the correct libcurl version is not used by curl. This results in errors when using curl:
```
$ curl --version
curl: symbol lookup error: curl: undefined symbol: curl_easy_ssls_export
```
See this discussion in the wofli repo: https://github.com/orgs/wolfi-dev/discussions/41391
=> Fix curl dependency issue

lib/crawler/coordinator.rb
Quick fix to ensure the logs accurately reflect the success or failure of a `urltest` crawl
The problem was caused by Crawler not knowing what 'stage' the `urltest` crawl is.
The `@crawl_stage` instance variable sets a key, either `CRAWL_STAGE_PRIMARY` or `CRAWL_STAGE_PURGE`, that is then used to update a value in `crawl_results` to either 'success' or 'failure'. This `crawl_results` gets sent back to the calling method in `lib/api/crawl.rb`, which ANDs the results of both CRAWL_STAGE_PRIMARY and CRAWL_STAGE_PURGE together and marks the entire crawl as either a success or failure.
In the case of `urltest`, the method never explicitly set the crawl stage to `CRAWL_STAGE_PRIMARY`, so `crawl_results` wasn't getting updated properly, thus resulting in a processed outcome of `failure`
- If …
=> Ensure run_urltest_crawl!() method sets the @crawl_stage instance variable

Gemfile, Gemfile.lock
This PR bumps `nokogiri` to 1.18.8, as 1.18.6 is vulnerable to a buffer under-read.
I don't think we are vulnerable, but this is a minor version bump and is trivial to do.
=> [Synk] [CVE-2025-32415] Bump Nokogiri to 1.18.8

lib/crawler/api/crawl.rb, lib/crawler/coordinator.rb, lib/crawler/output_sink/elasticsearch.rb, spec/lib/crawler/api/crawl_spec.rb
The aim of this PR is to print, in human-readable form, end-of-crawl stats as well as Elasticsearch-specific stats _if Elasticsearch is the designated output sink_.
The info printed is already captured by existing logging, so this data is purely for the sake of the user to have a nice, formatted output of stats.
Example output:
```
---- Crawl Stats ----
- Pages visited: 11
- URLs allowed: 10
- URLs denied
- Already seen: 91
- Domain filter: 9
- Crawl duration (seconds): 5
- Crawling time (seconds): 0.528
- Average response time (seconds): 0.048
---- Elasticsearch Ingestion Stats ----
- Completed
- Documents upserted: 9
- Volume (bytes): 14597
- Failed
- Number of documents that failed to index: 0
- Volume (bytes): 0
```
- If there is no GitHub issue, please create it. Each PR should have …
=> [GA] Pretty-print post-completion summary counters

lib/crawler/api/crawl.rb, lib/crawler/coordinator.rb, lib/crawler/data/crawl_result/base.rb, lib/crawler/data/crawl_result/redirect.rb, lib/crawler/data/crawl_result/sitemap.rb, lib/crawler/data/crawl_task.rb, lib/crawler/data/link.rb, lib/crawler/data/url_queue/base.rb, lib/crawler/data/url_queue/memory_only.rb, lib/crawler/event_generator.rb, lib/crawler/http_client.rb, lib/crawler/http_executor.rb, lib/crawler/http_utils/exceptions.rb, lib/crawler/output_sink/base.rb, lib/crawler/stats.rb, lib/crawler/url_validator.rb, lib/crawler/url_validator/url_content_check_concern.rb, lib/crawler/url_validator/url_request_check_concern.rb
The Open Crawler codebase is full of line break comments that look like:
```
```
The code base would look cleaner if we didn't have these, so this PR removes them.
=> Remove line break comments

lib/crawler/output_sink/file.rb, spec/lib/crawler/output_sink/file_spec.rb
This PR aims to make the File sink generate human-readable `json` files as opposed to the hash values it was previously using. The hash values were not human readable, which makes understanding their contents at a glance impossible.
Here is an example of the filenames with this change:
=> File sink generates human-readable filenames

lib/crawler/url_validator/url_request_check_concern.rb, spec/lib/crawler/url_validator/url_request_check_spec.rb
This PR replaces some links to Enterprise Search docs in the codebase to links to Open Crawler's configuration docs.
This isn't perfect (ideally we should point to docs of our own explaining proxy setup, auth config etc) but this at least gets mentions of `ent-search` out of Open Crawler.
If Open Crawler gets documentation for these specific features, these links to be updated to point to those.
=> Replaced links to ent-search docs with links to Crawler example config

.rubocop.yml, lib/crawler/api/config.rb, lib/crawler/content_engine/transformer.rb, lib/crawler/http_header_service.rb, lib/crawler/rule_engine/base.rb, lib/crawler/url_validator/dns_check_concern.rb, spec/lib/crawler/api/config_spec.rb
Add support for domain names and paths that use a different formatting (e.g.: UTF-8 instead of ASCII).
Changes:
- Normalize all domains, seed URLs, and sitemap URLs during initial config building stage
- This is done by overwriting the existing URL in memory, so the normalized one will be used everywhere else in the crawl run
- Use Addressable instead of ruby's built-in URI lib to parse config URLs
- Use normalized URL when using validate CLI command
- [Lint] Increase cyclomatic complexity from 7 to 8
=> Support internationalized domain names and paths

.buildkite/publish/test-docker.sh
The directory was changed from `/app` to `/home/app` on both the main and 0.2 branches, but this test was only fixed for main branch.
This PR fixes the test for the 0.2 branch so 0.2.x versions can continue to be released.
=> Fix release pipeline directory test

Dockerfile.wolfi
This will backport the following commits from `main` to `0.4`:
- [Update docker.elastic.co/wolfi/jdk:openjdk-21.35-r1 Docker digest to 56d6979 (#349)](https://github.com/elastic/crawler/pull/349)
=> [0.4] Update docker.elastic.co/wolfi/jdk:openjdk-21.35-r1 Docker digest to 56d6979 (#349)

Dockerfile.wolfi
This PR reverts the change made by this renovate [PR](https://github.com/elastic/crawler/pull/349)
=> Revert the Docker.wolfi base image back to a known working version

Dockerfile.wolfi
This will backport the following commits from `main` to `0.4`:
- [Revert the Docker.wolfi base image back to a known working version (#358)](https://github.com/elastic/crawler/pull/358)
=> [0.4] Revert the Docker.wolfi base image back to a known working version (#358)

.buildkite/pipeline.yml, .buildkite/scripts/run_command.sh, .buildkite/scripts/test-wolfi-image.sh, Dockerfile.wolfi, Makefile
`elastic-renovate` recently [bumped](https://github.com/elastic/crawler/pull/349) the sha for the base image of our wolfi docker image. Unfortunately that broke our image as `apk` has been stripped out, which requires a re-work of the Dockerfile. The regression slipped through the cracks because on CI we only build the simple Docker image (`Dockerfile`), not the wolfi one. Wolfi is only built at release time.
I tried a few different things to fix the new image, however it seems like it's a non-trivial amount of effort at this time, so we just [reverted the bump](https://github.com/elastic/crawler/pull/358). 
For future reference, I tried using `wget` instead of `curl`, as well as installing `curl` and `make` via another build stage (from an `alpine` image, and copy it into the next …
=> Build the wolfi image on CI

Dockerfile.wolfi
This PR pins the Git version to `2.45.0`, as the base image uses `2.43.0` which is affected by `CVE-2024-32002`
=> [CVE-2024-32002] Pin git version to 2.45.0 in Docker.wolfi

.backportrc.json
Minor update for `.backportrc.json` to allow backporting to `0.4` branch via the bot
=> Update backportrc to count main as 0.5.0

.buildkite/pipeline.yml, .buildkite/scripts/run_command.sh, .buildkite/scripts/test-wolfi-image.sh, Makefile
This will backport the following commits from `main` to `0.4`:
- [Build the wolfi image on CI (#357)](https://github.com/elastic/crawler/pull/357)
=> [0.4] Build the wolfi image on CI (#357)

Dockerfile.wolfi
This will backport the following commits from `main` to `0.4`:
- [Update docker.elastic.co/wolfi/chainguard-base:latest Docker digest to 5d0f094 (#382)](https://github.com/elastic/crawler/pull/382)
=> [0.4] Update docker.elastic.co/wolfi/chainguard-base:latest Docker digest to 5d0f094 (#382)

Dockerfile.wolfi
This will backport the following commits from `main` to `0.3`:
- [Update docker.elastic.co/wolfi/chainguard-base:latest Docker digest to 5d0f094 (#382)](https://github.com/elastic/crawler/pull/382)
=> [0.3] Update docker.elastic.co/wolfi/chainguard-base:latest Docker digest to 5d0f094 (#382)
